<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><title>管理员系统</title><link rel="stylesheet" href="/clinic-ui.css"><script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script></head>
<body><header class="app-header"><div class="brand">管理员系统</div><nav class="nav"><a href="/">患者端</a><a href="/admin/login">重新秘钥登录</a></nav></header>
<div class="layout"><aside class="sidebar"><a class="side-link" href="/admin/dashboard">Dashboard</a><a class="side-link" href="/admin/schedule/manage">排班管理</a><a class="side-link" href="/admin/doctor/manage">医生管理</a><a class="side-link" href="/admin/finance">财务流水</a></aside>
<main class="main">
<section id="panel-dashboard" class="admin-panel"><div class="page-title"><h2>经营数据大屏</h2><div><button class="btn secondary" onclick="loadStats(7)">近7天</button><button class="btn secondary" onclick="loadStats(30)">近30天</button><button class="btn" onclick="aggregateToday()">手动聚合今日</button></div></div><div class="stats-grid"><div class="card"><h3>科室就诊量</h3><div id="deptChart" class="chart"></div></div><div class="card"><h3>医生接诊率</h3><div id="doctorChart" class="chart"></div></div></div></section>
<section id="panel-schedule" class="admin-panel"><div class="page-title"><h2>排班管理</h2><button class="btn" onclick="loadSchedules()">刷新</button></div><div class="card"><div class="form-row"><input id="sDoctorId" placeholder="医生ID"><input id="sDeptId" placeholder="科室ID"><input id="sDate" type="date"><select id="sPeriod"><option value="AM">上午</option><option value="PM">下午</option></select><button class="btn success" onclick="createSchedule()">新增排班</button></div><div class="form-row"><input id="slotScheduleId" placeholder="排班ID"><input id="slotStart" value="08:00" placeholder="开始时间"><input id="slotEnd" value="08:30" placeholder="结束时间"><input id="slotQuota" type="number" value="10" placeholder="号源数"><button class="btn secondary" onclick="createSlot()">新增时段</button></div></div><table class="table"><thead><tr><th>ID</th><th>医生</th><th>科室</th><th>日期</th><th>时段</th><th>号源</th><th>操作</th></tr></thead><tbody id="scheduleRows"></tbody></table></section>
<section id="panel-doctor" class="admin-panel"><div class="page-title"><h2>医生管理</h2><button class="btn" onclick="loadDoctors()">刷新</button></div><div class="card"><div class="form-row"><input id="dName" placeholder="医生姓名"><input id="dTitle" placeholder="职称"><input id="dDeptId" placeholder="科室ID"><button class="btn success" onclick="createDoctor()">新增医生</button></div></div><table class="table"><thead><tr><th>ID</th><th>姓名</th><th>职称</th><th>科室</th><th>操作</th></tr></thead><tbody id="doctorRows"></tbody></table></section>
<section id="panel-finance" class="admin-panel"><div class="page-title"><h2>财务流水</h2></div><div class="card"><p class="muted">当前财务模块展示预约支付聚合入口，真实流水表可后续扩展。</p><button class="btn secondary" onclick="loadStats(30);showPanel('dashboard')">查看近30天经营数据</button></div></section>
</main></div><script src="/admin.js"></script></body></html>
